services:
  postgres:
    image: postgres:latest
    container_name: farmabusca-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "102030"
      POSTGRES_DB: farmabusca_db
    ports:
      - "5432:5432"
    volumes:
      - volume_name:/var/lib/postgresql/data

volumes:
  volume_name: # <- Rename "volume_name"
    name:
      volume_name
